[package]
name = "metaschemars"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rust library for parsing Metaschema module definitions"

[dependencies]
metaschemars-model = { path = "../metaschemars-model" }
metaschemars-yaml = { path = "../metaschemars-yaml" }

[features]
default = ["yaml"]
yaml = []
